apiVersion: serverless.vke.volcengine.com/v1alpha1
kind: SidecarConfig
metadata:
  labels:
    app.kubernetes.io/name: kidecar
  name: sidecarconfig-sample
spec:
  injection:
    selector:
      matchLabels:
        app: myapp
    injectSidecar: true
    namespaceSelector:
      matchLabels:
        app: myapp
    serviceAccountName: kidecar-sa
    shareProcessNamespace: true
  kidecar:
    plugins:
      hot_update:
        name: hot_update
        config:
          loadPatchType: "signal"
          fileDir: "/app/downloads"
          signal:
            signalName: "SIGHUP"
            processName: "nginx: master process nginx"
          storageConfig: # 存储配置
            type: InKube
            inKube:
              annotationKey: "sidecar.vke.volcengine.com/hot-update-result"
        bootOrder: 1
      restartPolicy: Always
      resources:
        CPU: 100m
        Memory: 128Mi
      sidecarStartOrder: Before
